from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path

from qis.spot_forecast import SpotForecast


def render_spot_dashboard(forecasts: list[SpotForecast], output: Path) -> Path:
    payload = json.dumps([asdict(item) for item in forecasts], ensure_ascii=False)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(HTML.replace("__FORECAST_DATA__", payload), encoding="utf-8")
    output.with_name("spot_forecasts.json").write_text(payload, encoding="utf-8")
    return output


HTML = r"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="data:,">
  <title>QIS 现货决策台</title>
  <style>
    :root {
      --ink0:#050c12;--ink1:#08131d;--ink2:#0d1a25;--ink3:#14232f;
      --line:rgba(193,210,221,.11);--line2:rgba(193,210,221,.22);
      --paper:#edf2f3;--muted:#748692;--gold:#cba45f;--gold2:#efca88;
      --green:#4ec9a2;--red:#ec7b73;
      --sans:"Avenir Next","PingFang SC","Microsoft YaHei",sans-serif;
      --display:"Songti SC","STSong",serif;--mono:"SFMono-Regular","Roboto Mono",monospace;
    }
    *{box-sizing:border-box} html{background:var(--ink0)} body{margin:0;color:var(--paper);font-family:var(--sans);
      background:linear-gradient(rgba(193,210,221,.025) 1px,transparent 1px),
      linear-gradient(90deg,rgba(193,210,221,.025) 1px,transparent 1px),var(--ink0);background-size:48px 48px}
    button,input,select,textarea{font:inherit} button{color:inherit}.positive{color:var(--green)!important}.negative{color:var(--red)!important}
    .topbar{position:sticky;top:0;z-index:20;min-height:66px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 28px;background:rgba(5,12,18,.94);border-bottom:1px solid var(--line);backdrop-filter:blur(14px)}
    .brand{display:flex;align-items:center;gap:13px}.mark{width:27px;height:27px;display:flex;gap:4px;align-items:flex-end}.mark i{width:3px;background:var(--gold)}.mark i:nth-child(1){height:11px}.mark i:nth-child(2){height:25px}.mark i:nth-child(3){height:17px}
    .brand strong{display:block;font-family:var(--display);font-size:17px;letter-spacing:.08em}.brand small{display:block;color:var(--muted);font:9px/1.4 var(--mono);letter-spacing:.14em}
    .product-nav{display:flex;align-self:stretch}.product-nav button{position:relative;border:0;background:none;color:var(--muted);padding:0 20px;cursor:pointer;font-size:12px}.product-nav button:after{content:"";position:absolute;left:20px;right:20px;bottom:0;height:2px;background:transparent}.product-nav button.active{color:var(--paper)}.product-nav button.active:after{background:var(--gold)}
    .status{display:flex;gap:14px;align-items:center;color:var(--muted);font:10px var(--mono)}.pulse{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px rgba(78,201,162,.1)}
    .actions{display:flex;gap:9px}.button{border:1px solid var(--line2);background:transparent;padding:9px 14px;cursor:pointer;border-radius:2px;font-size:11px}.button:hover{border-color:var(--gold);color:var(--gold2)}.button.primary{color:#17130c;background:var(--gold);border-color:var(--gold);font-weight:700}.button.primary:hover{color:#17130c;background:var(--gold2)}
    main{max-width:1500px;margin:auto;padding:28px}.view{display:none}.view.active{display:block}.market-head{display:flex;align-items:flex-end;justify-content:space-between;gap:28px;margin-bottom:20px}
    .radar-head{display:flex;align-items:end;justify-content:space-between;gap:24px;margin-bottom:16px}.radar-head h1{margin:0;font:500 clamp(30px,4vw,48px)/1.1 var(--display)}.radar-head p{margin:9px 0 0;color:var(--muted);font-size:11px}.radar-tools{display:flex;gap:8px}.radar-tools input,.radar-tools select{width:auto;min-width:150px;padding:9px 11px}.radar-table{margin-bottom:24px}.radar-table table{box-shadow:none}.radar-table th{background:rgba(13,26,37,.85)}.radar-table tbody tr:hover{background:rgba(203,164,95,.055)}.radar-table td{height:58px}.rank{color:var(--gold2);font:12px var(--mono)}.score{font:600 12px var(--mono)}.score small{display:block;color:var(--muted);font:8px var(--sans);margin-top:4px}.asset-id strong{display:block;font:13px var(--mono)}.asset-id small{color:var(--muted);font-size:9px}.signal-cell strong{display:block}.signal-cell small{color:var(--muted);font-size:9px}.row-actions{display:flex;gap:7px}.mini-button{border:1px solid var(--line2);background:transparent;padding:6px 9px;cursor:pointer;font-size:9px;white-space:nowrap}.mini-button:hover{color:var(--gold2);border-color:var(--gold)}.mini-button.buy-now{color:var(--gold2)}.pagination{display:flex;align-items:center;justify-content:space-between;padding:13px 16px;border-top:1px solid var(--line);color:var(--muted);font-size:10px}.page-buttons{display:flex;gap:6px}.page-buttons button{min-width:31px;border:1px solid var(--line);background:transparent;padding:6px;color:var(--muted);cursor:pointer}.page-buttons button.active{color:var(--ink0);background:var(--gold);border-color:var(--gold)}.detail-page{display:none}.detail-page.active{display:block}.radar-list.hidden{display:none}.detail-label{display:flex;align-items:center;justify-content:space-between;margin:0 0 22px;padding-bottom:18px;border-bottom:1px solid var(--line)}.detail-label h1{margin:0;font:500 clamp(28px,4vw,45px)/1.1 var(--display)}.back-button{border:0;background:none;color:var(--gold2);padding:8px 0;cursor:pointer;font-size:11px}
    .eyebrow{color:var(--gold);font:10px var(--mono);letter-spacing:.18em;text-transform:uppercase;margin-bottom:8px}.instrument{display:flex;align-items:center;gap:16px}.seal{width:47px;height:47px;display:grid;place-items:center;border:1px solid var(--line2);color:var(--gold2);font:11px var(--mono);transform:rotate(45deg)}.seal span{transform:rotate(-45deg)}
    select{color:var(--paper);background:var(--ink1);border:1px solid var(--line);padding:11px 34px 11px 13px}.quote{text-align:right}.quote label{display:block;color:var(--muted);font-size:10px;margin-bottom:5px}.quote strong{font:500 31px var(--mono)}.quote .change{margin-left:12px;font:12px var(--mono)}.quote small{display:block;margin-top:8px;color:var(--muted)}
    .panel{background:rgba(8,19,29,.84);border:1px solid var(--line)}.chartbar{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;border-bottom:1px solid var(--line)}.tabs{display:flex;gap:8px}.tabs button{min-width:58px;border:0;border-bottom:2px solid transparent;background:none;color:var(--muted);padding:8px;cursor:pointer;font:11px var(--mono)}.tabs button.active{color:var(--gold2);border-color:var(--gold)}.legend{color:var(--muted);font-size:10px}
    .chart{height:340px;padding:14px 20px}.chart svg{width:100%;height:100%;overflow:visible}.grid{stroke:rgba(193,210,221,.08)}.actual{fill:none;stroke:#9fb4c1;stroke-width:2}.prediction{fill:none;stroke:var(--gold);stroke-width:2.5;stroke-dasharray:7 5}.range{fill:rgba(203,164,95,.13)}.now{stroke:rgba(203,164,95,.35);stroke-dasharray:4 4}
    .rail{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid var(--line)}.forecast{position:relative;text-align:left;padding:16px 18px 18px;background:transparent;border:0;border-right:1px solid var(--line);cursor:pointer}.forecast:last-child{border-right:0}.forecast:hover,.forecast.active{background:rgba(203,164,95,.05)}.forecast span,.forecast em{display:block;color:var(--muted);font-size:9px;font-style:normal}.forecast strong{display:block;margin:7px 0 3px;font:14px var(--mono)}.meter{height:2px;background:var(--ink3);margin-top:8px}.meter i{display:block;height:100%;background:var(--gold)}
    .decision-grid{display:grid;grid-template-columns:1.55fr .85fr;gap:18px;margin-top:18px}.card{padding:24px}.heading{display:flex;align-items:flex-start;justify-content:space-between;gap:15px}h2{margin:0;font:600 23px/1.25 var(--display)}.badge{color:var(--gold2);background:rgba(203,164,95,.09);border:1px solid rgba(203,164,95,.24);padding:7px 10px;font-size:10px}.summary{color:#aab7bf;font-size:13px;line-height:1.9;margin:20px 0}.summary strong{color:var(--paper);font-family:var(--mono)}
    .levels{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line)}.levels div{padding:14px;border-right:1px solid var(--line)}.levels div:last-child{border-right:0}.levels span{display:block;color:var(--muted);font-size:9px;margin-bottom:7px}.levels strong{font:12px var(--mono)}.factors{display:flex;flex-wrap:wrap;gap:20px;margin-top:17px;color:var(--muted);font-size:10px}.factors b{color:var(--paper);margin-left:4px}
    .reliability{display:flex;gap:20px;align-items:center;margin:19px 0}.ring{--p:0%;width:88px;aspect-ratio:1;border-radius:50%;background:conic-gradient(var(--gold) var(--p),var(--ink3) 0);display:grid;place-items:center}.ring:before{content:"";width:70px;aspect-ratio:1;border-radius:50%;background:var(--ink1);grid-area:1/1}.ring strong,.ring small{grid-area:1/1;z-index:1}.ring strong{font:19px var(--mono);transform:translateY(-5px)}.ring small{color:var(--muted);font:8px var(--mono);transform:translateY(12px)}.reliability-copy p{color:var(--muted);font-size:11px;line-height:1.8}
    .period-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:var(--line)}.period-metrics div{background:var(--ink1);padding:10px}.period-metrics span{display:block;color:var(--muted);font-size:8px}.period-metrics strong{font:10px/1.8 var(--mono)}
    .records{margin-top:18px;padding:24px}.records-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:15px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th{color:#687985;font:9px var(--mono);text-align:left;padding:11px 13px;border-bottom:1px solid var(--line)}td{padding:14px 13px;border-bottom:1px solid rgba(193,210,221,.08);color:#afbbc2;font-size:11px}td strong{color:var(--paper);font:11px/1.8 var(--mono)}.tag{font-size:9px;color:var(--green)}.tag.closed{color:var(--muted)}.link{border:0;background:none;color:var(--gold2);cursor:pointer}
    .sentinel-head{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:24px;padding:14px 0 25px;border-bottom:1px solid var(--line)}.sentinel-head h1{max-width:780px;margin:0;font:500 clamp(30px,4vw,54px)/1.12 var(--display);letter-spacing:.01em}.sentinel-head p{max-width:650px;margin:12px 0 0;color:#94a4ae;font-size:12px;line-height:1.9}.scope-note{max-width:270px;padding:14px 16px;border:1px solid var(--line);color:var(--muted);font-size:10px;line-height:1.7}.scope-note b{display:block;color:var(--gold2);font:10px var(--mono);margin-bottom:5px}
    .sentinel-metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);margin:18px 0}.sentinel-metrics div{padding:17px 19px;border-right:1px solid var(--line)}.sentinel-metrics div:last-child{border-right:0}.sentinel-metrics span{display:block;color:var(--muted);font-size:9px}.sentinel-metrics strong{display:block;margin-top:7px;font:19px var(--mono)}
    .position-list{display:grid;gap:12px}.position-card{display:grid;grid-template-columns:1.1fr .85fr .85fr 1.4fr auto;align-items:center;gap:18px;padding:20px 22px;background:var(--ink1);border:1px solid var(--line)}.position-card:hover{border-color:var(--line2)}.position-name strong{display:block;font:18px var(--mono)}.position-name span,.position-cell span{display:block;color:var(--muted);font-size:9px;margin-bottom:7px}.position-name small,.position-cell small{display:block;margin-top:6px;color:#9babb5;font-size:10px;line-height:1.6}.position-cell strong{display:block;font:12px var(--mono)}.risk-bar{height:3px;margin-top:9px;background:var(--ink3)}.risk-bar i{display:block;height:100%;background:var(--green)}.risk-bar.medium i{background:var(--gold)}.risk-bar.high i{background:var(--red)}.action{display:inline-block;margin-bottom:7px;color:var(--green);font:10px var(--mono)}.action.protect,.action.reduce{color:var(--gold2)}.action.exit{color:var(--red)}.reason{color:#94a4ae;font-size:10px;line-height:1.7;white-space:normal}.empty{padding:70px 24px;text-align:center;border:1px dashed var(--line2);color:var(--muted)}.empty strong{display:block;color:var(--paper);font:22px var(--display);margin-bottom:9px}
    dialog{width:min(560px,calc(100% - 28px));color:var(--paper);background:var(--ink1);border:1px solid var(--line2);padding:0}dialog::backdrop{background:rgba(2,7,11,.76);backdrop-filter:blur(5px)}.dialog-head{display:flex;align-items:center;justify-content:space-between;padding:20px 22px;border-bottom:1px solid var(--line)}.dialog-body{padding:22px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}label span{display:block;color:var(--muted);font-size:10px;margin-bottom:7px}input,textarea{width:100%;color:var(--paper);background:var(--ink0);border:1px solid var(--line);padding:11px 12px}textarea{min-height:78px;resize:vertical}.full{grid-column:1/-1}.dialog-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}
    .advice{position:fixed;z-index:40;top:0;right:0;width:min(470px,100%);height:100vh;padding:30px;background:var(--ink1);border-left:1px solid var(--line2);transform:translateX(102%);transition:.3s;overflow:auto}.advice.open{transform:translateX(0)}.advice-item{padding:17px 0;border-bottom:1px solid var(--line)}.advice-item span{color:var(--gold);font:9px var(--mono)}.advice-item h3{margin:6px 0;font-size:14px}.advice-item p{margin:0;color:var(--muted);font-size:11px;line-height:1.8}
    .spirit-button{position:fixed;z-index:55;right:24px;bottom:24px;width:58px;height:58px;border:1px solid rgba(203,164,95,.55);border-radius:50%;background:radial-gradient(circle at 36% 30%,#f4d99f 0 7%,#cba45f 8% 19%,#14232f 20% 100%);box-shadow:0 0 0 7px rgba(203,164,95,.07),0 16px 36px rgba(0,0,0,.38);cursor:pointer}.spirit-button:before,.spirit-button:after{content:"";position:absolute;top:23px;width:4px;height:4px;border-radius:50%;background:var(--gold2);box-shadow:0 0 7px var(--gold2)}.spirit-button:before{left:19px}.spirit-button:after{right:19px}.spirit-button span{position:absolute;right:67px;top:12px;width:max-content;padding:8px 10px;color:var(--gold2);background:var(--ink1);border:1px solid var(--line2);font:10px var(--mono);opacity:0;transform:translateX(7px);transition:.2s;pointer-events:none}.spirit-button:hover span,.spirit-button:focus-visible span{opacity:1;transform:none}
    .assistant{position:fixed;z-index:60;right:20px;bottom:20px;width:min(430px,calc(100% - 24px));height:min(700px,calc(100vh - 40px));display:grid;grid-template-rows:auto auto 1fr auto;background:rgba(8,19,29,.98);border:1px solid var(--line2);box-shadow:0 25px 70px rgba(0,0,0,.5);transform:translateY(24px) scale(.97);transform-origin:bottom right;opacity:0;pointer-events:none;transition:.24s}.assistant.open{transform:none;opacity:1;pointer-events:auto}.assistant-head{display:flex;align-items:center;justify-content:space-between;padding:19px 20px;border-bottom:1px solid var(--line)}.assistant-title{display:flex;align-items:center;gap:11px}.assistant-orb{width:30px;height:30px;border-radius:50%;border:1px solid var(--gold);display:grid;place-items:center;color:var(--gold2);font:12px var(--display);box-shadow:inset 0 0 14px rgba(203,164,95,.15)}.assistant-title strong{display:block;font:16px var(--display)}.assistant-title small{display:block;margin-top:3px;color:var(--muted);font:8px var(--mono)}.assistant-context{display:flex;gap:7px;overflow:auto;padding:10px 14px;border-bottom:1px solid var(--line)}.context-chip{white-space:nowrap;padding:6px 8px;color:var(--muted);background:var(--ink0);border:1px solid var(--line);font:8px var(--mono)}.context-chip.active{color:var(--gold2);border-color:rgba(203,164,95,.35)}.assistant-messages{overflow:auto;padding:18px;display:flex;flex-direction:column;gap:13px}.message{max-width:88%;padding:12px 14px;white-space:pre-wrap;font-size:12px;line-height:1.75}.message.user{align-self:flex-end;color:var(--ink0);background:var(--gold2)}.message.assistant{align-self:flex-start;background:var(--ink3);border-left:2px solid var(--gold)}.message.system{align-self:stretch;max-width:none;color:var(--muted);border:1px dashed var(--line2);background:transparent}.message small{display:block;margin-top:8px;color:var(--muted);font:8px var(--mono)}.assistant-evidence{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.assistant-evidence span{padding:4px 6px;color:var(--gold2);border:1px solid rgba(203,164,95,.25);font:8px var(--mono)}.assistant-prompts{display:flex;gap:6px;overflow:auto;padding:0 14px 10px}.assistant-prompts button{white-space:nowrap;padding:7px 9px;color:var(--muted);background:transparent;border:1px solid var(--line);cursor:pointer;font-size:9px}.assistant-prompts button:hover{color:var(--gold2);border-color:var(--gold)}.assistant-form{padding:13px 14px 14px;border-top:1px solid var(--line)}.assistant-form textarea{min-height:62px;max-height:130px}.assistant-form-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:9px}.assistant-model{color:var(--muted);font:8px var(--mono)}.assistant-model.ready{color:var(--green)}.toast{position:fixed;z-index:80;left:50%;bottom:25px;transform:translate(-50%,20px);background:var(--paper);color:var(--ink0);padding:11px 18px;opacity:0;transition:.25s}.toast.show{opacity:1;transform:translate(-50%,0)}
    @media(max-width:1050px){.status{display:none}.position-card{grid-template-columns:1fr 1fr}.position-card .position-decision{grid-column:1/-1}}@media(max-width:900px){.topbar{padding:12px 16px;flex-wrap:wrap}.product-nav{order:3;width:100%;height:42px}.product-nav button{flex:1}.actions{margin-left:auto}main{padding:18px 14px}.radar-head{align-items:stretch;flex-direction:column}.radar-tools{width:100%}.radar-tools input,.radar-tools select{flex:1;min-width:0}.radar-table{overflow:auto}.radar-table table{min-width:920px}.decision-grid{grid-template-columns:1fr}.rail{overflow:auto;grid-template-columns:repeat(5,minmax(130px,1fr))}.period-metrics{grid-template-columns:repeat(2,1fr)}.sentinel-metrics{grid-template-columns:repeat(2,1fr)}.sentinel-metrics div:nth-child(2){border-right:0}.sentinel-metrics div:nth-child(-n+2){border-bottom:1px solid var(--line)}}@media(max-width:580px){.brand small{display:none}.market-head,.sentinel-head{display:block}.scope-note{margin-top:18px;max-width:none}.quote{text-align:left;margin-top:20px}.chart{height:250px;padding:8px}.levels{grid-template-columns:1fr}.levels div{border-right:0;border-bottom:1px solid var(--line)}.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.position-card{grid-template-columns:1fr}.position-card .position-decision{grid-column:auto}.spirit-button{right:14px;bottom:14px}.assistant{right:8px;bottom:8px;width:calc(100% - 16px);height:calc(100vh - 16px)}}
  </style>
</head>
<body>
  <header class="topbar"><div class="brand"><span class="mark"><i></i><i></i><i></i></span><div><strong>QIS 决策终端</strong><small>QUANT INTELLIGENCE SYSTEM</small></div></div><nav class="product-nav" aria-label="看盘模式"><button class="active" data-view="opportunity">机会雷达</button><button data-view="sentinel">持仓哨兵 <span id="openCount"></span></button></nav><div class="status"><span class="pulse"></span><span>股票与加密货币</span><span>只分析 · 不自动下单</span></div><div class="actions"><button class="button" id="adviceBtn">模型诊断</button><button class="button primary" id="buyBtn">登记买入</button></div></header>
  <main>
    <div class="view active" id="opportunityView"><div class="radar-list" id="radarList">
    <section class="radar-head"><div><div class="eyebrow">MARKET OPPORTUNITY MATRIX</div><h1>机会雷达</h1><p>默认按多周期概率、收益、置信度与趋势一致性综合排序，优质标的优先。</p></div><div class="radar-tools"><input id="radarSearch" placeholder="搜索标的"><select id="radarMarket"><option value="">全部市场</option><option value="现货">加密货币</option><option value="股票">股票</option></select><select id="radarSort"><option value="score">综合机会分</option><option value="probability">上涨概率</option><option value="return">1月预期收益</option><option value="daily">今日涨幅</option></select></div></section>
    <section class="panel radar-table"><div class="table-wrap"><table><thead><tr><th>排名</th><th>标的</th><th>机会分</th><th>最新价</th><th>日涨跌</th><th>1周预测</th><th>1月预测</th><th>3月预测</th><th>策略</th><th>操作</th></tr></thead><tbody id="radarRows"></tbody></table></div><div class="pagination"><span id="pageInfo"></span><div class="page-buttons" id="pageButtons"></div></div></section>
    </div><div class="detail-page" id="detailPage">
    <div class="detail-label"><div><button class="back-button" id="backToRadar">← 返回机会雷达</button><div class="eyebrow">INSTRUMENT INTELLIGENCE</div><h1 id="detailTitle">标的深度分析</h1></div><button class="button primary" id="detailBuy">登记买入</button></div>
    <section class="market-head"><div><div class="eyebrow" id="marketType">现货 · USDT 市场</div><div class="instrument"><div class="seal"><span id="seal">BTC</span></div><select id="asset"></select></div></div><div class="quote"><label>OKX 最新成交价</label><strong id="price">--</strong><span id="change" class="change">--</span><small id="regime"></small><small id="quoteTime"></small></div></section>
    <section class="panel"><div class="chartbar"><div class="tabs" id="tabs"></div><div class="legend">历史价格 ─　预测中枢 ┄　金色区间＝预测范围</div></div><div class="chart"><svg id="svg" viewBox="0 0 1000 320" preserveAspectRatio="none"></svg></div><div class="rail" id="rail"></div></section>
    <section class="decision-grid"><article class="panel card"><div class="heading"><div><div class="eyebrow">当前策略</div><h2 id="decision">--</h2></div><span class="badge" id="signal">--</span></div><p class="summary" id="summary"></p><div class="levels"><div><span>建议买入区间</span><strong id="zone"></strong></div><div><span>当前周期目标</span><strong class="positive" id="target"></strong></div><div><span>决策失效位</span><strong class="negative" id="invalid"></strong></div></div><div class="factors" id="factors"></div></article>
      <article class="panel card"><div class="heading"><div><div class="eyebrow">每小时预测反推</div><h2>策略自优化</h2></div><button class="link" id="openAdvice">查看改进建议 →</button></div><div class="reliability"><div class="ring" id="ring"><strong id="score">--</strong><small>方向命中</small></div><div class="reliability-copy"><strong id="rank">等待预测到期</strong><p id="reliabilityText">每小时冻结一次预测，周期到期后与真实价格反推并校准后续策略。</p></div></div><div class="period-metrics" id="periodMetrics"></div></article></section>
    </div></div>
    <div class="view" id="sentinelView">
      <section class="sentinel-head"><div><div class="eyebrow">POST-ENTRY RISK COMMAND</div><h1>持仓哨兵</h1><p>只监控你手动登记的买入记录。系统持续重估退出概率、动态保护位和持有周期，负责把“何时卖”变成可解释的风险纪律。</p></div><div class="scope-note"><b>监控边界</b>不会扫描未登记资产，也不会自动卖出。仅覆盖已登记的股票与加密货币。</div></section>
      <section class="sentinel-metrics"><div><span>监控中持仓</span><strong id="metricOpen">0</strong></div><div><span>组合浮动盈亏</span><strong id="metricPnl">--</strong></div><div><span>高风险预警</span><strong id="metricRisk">0</strong></div><div><span>建议减仓 / 退出</span><strong id="metricExit">0</strong></div></section>
      <section class="position-list" id="positionList"></section>
      <section class="panel records"><div class="records-head"><div><div class="eyebrow">AUDIT TRAIL</div><h2>买入与卖出登记</h2></div><button class="button" id="refresh">刷新分析</button></div><div class="table-wrap"><table><thead><tr><th>状态</th><th>标的</th><th>周期</th><th>买入</th><th>数量</th><th>卖出</th><th>收益率</th><th>操作</th></tr></thead><tbody id="records"></tbody></table></div></section>
    </div>
  </main>
  <dialog id="buyDialog"><form id="buyForm"><div class="dialog-head"><div><div class="eyebrow">手动记录</div><h2>登记买入</h2></div><button type="button" class="button" data-close="buyDialog">关闭</button></div><div class="dialog-body"><div class="form-grid"><label><span>标的</span><input id="buyInst" readonly></label><label><span>预测周期</span><select id="buyPeriod"></select></label><label><span>买入价格</span><input id="buyPrice" type="number" step="any" required></label><label><span>买入数量</span><input id="quantity" type="number" step="any" min="0" required></label><label class="full"><span>备注</span><textarea id="notes"></textarea></label></div><div class="dialog-actions"><button type="button" class="button" data-close="buyDialog">取消</button><button class="button primary">保存买入</button></div></div></form></dialog>
  <dialog id="sellDialog"><form id="sellForm"><div class="dialog-head"><h2>登记卖出</h2><button type="button" class="button" data-close="sellDialog">关闭</button></div><div class="dialog-body"><input id="sellId" type="hidden"><label><span>卖出价格</span><input id="sellPrice" type="number" step="any" required></label><div class="dialog-actions"><button type="button" class="button" data-close="sellDialog">取消</button><button class="button primary">确认卖出</button></div></div></form></dialog>
  <aside class="advice" id="advice"><div class="heading"><div><div class="eyebrow">历史预测评估</div><h2>模型改进建议</h2></div><button class="button" id="closeAdvice">关闭</button></div><p class="summary">建议仅依据历史预测与到期真实行情的差异生成，不使用你的手动买卖结果。</p><div id="adviceList"></div></aside>
  <button class="spirit-button" id="assistantButton" aria-label="打开决策小精灵"><span>问问决策小精灵</span></button>
  <aside class="assistant" id="assistant" aria-label="决策小精灵">
    <div class="assistant-head"><div class="assistant-title"><span class="assistant-orb">策</span><div><strong>决策小精灵</strong><small>CONTEXT-AWARE DECISION COPILOT</small></div></div><button class="button" id="closeAssistant">收起</button></div>
    <div class="assistant-context"><span class="context-chip active" id="assistantAsset">当前标的</span><span class="context-chip">策略校准</span><span class="context-chip">持仓风险</span><span class="context-chip">历史命中</span></div>
    <div class="assistant-messages" id="assistantMessages"><div class="message system">我会关联当前标的预测、策略校准、持仓风险和历史命中率来回答。你做决定，我负责把依据和风险摊开。</div></div>
    <div><div class="assistant-prompts"><button data-prompt="结合当前预测和历史命中率，现在适合介入吗？">是否适合介入</button><button data-prompt="如果我已经持有，当前最需要防范什么风险？">持仓风险</button><button data-prompt="比较各周期信号，给我一个有失效条件的行动方案。">行动方案</button></div><form class="assistant-form" id="assistantForm"><textarea id="assistantQuestion" maxlength="2000" placeholder="例如：BTC 现在适合分批买入吗？"></textarea><div class="assistant-form-row"><span class="assistant-model" id="assistantModel">正在读取模型配置…</span><button class="button primary" id="assistantSend">分析决策</button></div></form></div>
  </aside>
  <div class="toast" id="toast"></div>
  <script>
    const data=__FORECAST_DATA__, labels={'1d':'1天','1w':'1周','1m':'1月','3m':'3月','6m':'6月'},pageSize=10;let asset=data[0],period='1d',radarPage=1,assistantHistory=[],state={positions:[],analyses:[],trade_stats:{overall:{},by_horizon:{}},model_evaluation:{overall:{},by_horizon:{}},strategy_adjustments:{},advice:[]};
    const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:6}),pct=n=>`${n>=0?'+':''}${(n*100).toFixed(2)}%`;
    function init(){ $('asset').innerHTML=data.map(x=>`<option value="${x.inst_id}">${x.symbol} / USDT · ${x.market_type}</option>`).join('');$('asset').onchange=e=>openDetail(e.target.value);$('radarSearch').oninput=()=>{radarPage=1;renderRadar()};$('radarMarket').onchange=()=>{radarPage=1;renderRadar()};$('radarSort').onchange=()=>{radarPage=1;renderRadar()};$('backToRadar').onclick=showRadar;$('detailBuy').onclick=openBuy;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('buyBtn').onclick=()=>{if($('detailPage').classList.contains('active'))openBuy();else openDetail(radarData()[0]?.inst_id||asset.inst_id)};$('adviceBtn').onclick=openAdvice;$('openAdvice').onclick=openAdvice;$('closeAdvice').onclick=()=> $('advice').classList.remove('open');$('assistantButton').onclick=openAssistant;$('closeAssistant').onclick=()=> $('assistant').classList.remove('open');$('assistantForm').onsubmit=askAssistant;document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('assistantQuestion').value=b.dataset.prompt;$('assistantQuestion').focus()});$('refresh').onclick=load;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('buyForm').onsubmit=buy;$('sellForm').onsubmit=sell;renderRadar();render();load();loadAssistantStatus();applyRoute();window.addEventListener('hashchange',applyRoute);refreshQuotes();setInterval(refreshQuotes,5000)}
    function switchView(name){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('opportunityView').classList.toggle('active',name==='opportunity');$('sentinelView').classList.toggle('active',name==='sentinel');if(name==='opportunity'){showRadar();location.hash='opportunity'}else location.hash='sentinel';$('buyBtn').style.display=name==='opportunity'?'':'none'}
    function opportunityScore(x){const w=horizon(x,'1w'),m=horizon(x,'1m'),q=horizon(x,'3m'),prob=w.up_probability*.25+m.up_probability*.45+q.up_probability*.30,ret=w.expected_return*.20+m.expected_return*.45+q.expected_return*.35,conf=w.confidence*.25+m.confidence*.45+q.confidence*.30,agree=[w,m,q].filter(f=>f.expected_return>0).length/3,retQuality=Math.max(0,Math.min(1,(ret+.02)/.18)),penalty=Math.min(12,x.volatility*120);return Math.max(0,Math.min(100,Math.round((prob*.38+retQuality*.27+conf*.20+agree*.15)*100-penalty)))}
    function radarData(){const q=$('radarSearch').value.trim().toLowerCase(),market=$('radarMarket').value,sort=$('radarSort').value;const rows=data.filter(x=>(!q||`${x.symbol} ${x.inst_id}`.toLowerCase().includes(q))&&(!market||x.market_type.includes(market)));return rows.sort((a,b)=>{if(sort==='probability')return horizon(b,'1m').up_probability-horizon(a,'1m').up_probability;if(sort==='return')return horizon(b,'1m').expected_return-horizon(a,'1m').expected_return;if(sort==='daily')return b.daily_change-a.daily_change;return opportunityScore(b)-opportunityScore(a)||horizon(b,'1m').up_probability-horizon(a,'1m').up_probability})}
    function horizon(x,key){return x.forecasts.find(f=>f.key===key)||x.forecasts[0]}
    function renderRadar(){const rows=radarData(),pages=Math.max(1,Math.ceil(rows.length/pageSize));radarPage=Math.min(radarPage,pages);const start=(radarPage-1)*pageSize,slice=rows.slice(start,start+pageSize);$('radarRows').innerHTML=slice.length?slice.map((x,i)=>{const w=horizon(x,'1w'),m=horizon(x,'1m'),q=horizon(x,'3m'),score=opportunityScore(x);return `<tr data-inst="${x.inst_id}"><td class="rank">#${start+i+1}</td><td class="asset-id"><strong>${x.symbol}</strong><small>${x.market_type}</small></td><td class="score">${score}<small>/ 100</small></td><td><strong>${fmt(x.current_price)}</strong></td><td class="${x.daily_change>=0?'positive':'negative'}">${pct(x.daily_change)}</td><td class="signal-cell"><strong class="${w.expected_return>=0?'positive':'negative'}">${pct(w.expected_return)}</strong><small>上涨 ${(w.up_probability*100).toFixed(0)}%</small></td><td class="signal-cell"><strong class="${m.expected_return>=0?'positive':'negative'}">${pct(m.expected_return)}</strong><small>上涨 ${(m.up_probability*100).toFixed(0)}%</small></td><td class="signal-cell"><strong class="${q.expected_return>=0?'positive':'negative'}">${pct(q.expected_return)}</strong><small>上涨 ${(q.up_probability*100).toFixed(0)}%</small></td><td><span class="badge">${x.decision}</span></td><td><div class="row-actions"><button class="mini-button" data-detail="${x.inst_id}">深度分析</button><button class="mini-button buy-now" data-buy="${x.inst_id}">登记买入</button></div></td></tr>`}).join(''):'<tr><td colspan="10">没有符合条件的标的。</td></tr>';$('pageInfo').textContent=`共 ${rows.length} 个标的 · 第 ${radarPage}/${pages} 页 · 优质标的优先`;$('pageButtons').innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===radarPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');$('radarRows').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));$('radarRows').querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{selectAsset(b.dataset.buy);openBuy()});$('pageButtons').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{radarPage=+b.dataset.page;renderRadar()})}
    function selectAsset(inst){asset=data.find(x=>x.inst_id===inst)||asset;$('asset').value=asset.inst_id;$('assistantAsset').textContent=`${asset.symbol} · ${labels[period]}`;render();renderRadar()}
    function openDetail(inst){selectAsset(inst);$('radarList').classList.add('hidden');$('detailPage').classList.add('active');$('detailTitle').textContent=`${asset.symbol} 深度分析`;$('buyBtn').style.display='';location.hash=`detail=${encodeURIComponent(inst)}`;window.scrollTo({top:0,behavior:'smooth'})}
    function showRadar(){ $('radarList').classList.remove('hidden');$('detailPage').classList.remove('active');$('buyBtn').style.display='';if(location.hash.startsWith('#detail='))history.replaceState(null,'',location.pathname+location.search+'#opportunity');window.scrollTo({top:0,behavior:'smooth'})}
    function applyRoute(){const hash=location.hash;if(hash==='#sentinel'){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='sentinel'));$('opportunityView').classList.remove('active');$('sentinelView').classList.add('active');$('buyBtn').style.display='none';return}document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='opportunity'));$('opportunityView').classList.add('active');$('sentinelView').classList.remove('active');if(hash.startsWith('#detail=')){const inst=decodeURIComponent(hash.slice(8));if(data.some(x=>x.inst_id===inst)){selectAsset(inst);$('radarList').classList.add('hidden');$('detailPage').classList.add('active');$('detailTitle').textContent=`${asset.symbol} 深度分析`;return}}$('radarList').classList.remove('hidden');$('detailPage').classList.remove('active')}
    function render(){if(!asset)return;const qt=new Date(asset.quote_time),lag=Math.max(0,Math.round((Date.now()-qt.getTime())/60000));$('marketType').textContent=`${asset.market_type} · USDT 市场`;$('seal').textContent=asset.symbol.slice(0,4);$('price').textContent=fmt(asset.current_price);$('change').textContent=pct(asset.daily_change);$('change').className=`change ${asset.daily_change>=0?'positive':'negative'}`;$('regime').textContent=`${asset.regime} · 日波动 ${(asset.volatility*100).toFixed(2)}%`;$('quoteTime').textContent=`${asset.quote_source} · 行情时间 ${qt.toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'})} · ${lag<=2?'实时':`延迟约 ${lag} 分钟`}`;
      $('assistantAsset').textContent=`${asset.symbol} · ${labels[period]}`;$('tabs').innerHTML=asset.forecasts.map(x=>`<button class="${x.key===period?'active':''}" data-p="${x.key}">${x.label}</button>`).join('');$('tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{period=b.dataset.p;render()});
      $('rail').innerHTML=asset.forecasts.map(x=>`<button class="forecast ${x.key===period?'active':''}" data-p="${x.key}"><span>${x.label}预测</span><strong>${fmt(x.target)}</strong><small class="${x.expected_return>=0?'positive':'negative'}">${pct(x.expected_return)} · ${x.signal}</small><em>上涨概率 ${(x.up_probability*100).toFixed(1)}%</em><span class="meter"><i style="width:${x.confidence*100}%"></i></span></button>`).join('');$('rail').querySelectorAll('button').forEach(b=>b.onclick=()=>{period=b.dataset.p;render()});
      const f=asset.forecasts.find(x=>x.key===period);$('decision').textContent=asset.decision;$('signal').textContent=f.signal;$('summary').innerHTML=`${asset.symbol} 的 ${f.label}预测中枢为 <strong>${fmt(f.target)}</strong>，区间 ${fmt(f.low)}–${fmt(f.high)}。上涨概率 ${(f.up_probability*100).toFixed(1)}%，只在买入区间内分批执行。`;$('zone').textContent=`${fmt(asset.buy_zone_low)} – ${fmt(asset.buy_zone_high)}`;$('target').textContent=fmt(f.target);$('invalid').textContent=fmt(asset.invalidation);$('factors').innerHTML=Object.entries(asset.factors).map(([k,v])=>`<span>${{trend:'趋势',momentum:'动量',volatility:'波动',agreement:'周期共振'}[k]||k}<b>${v}</b></span>`).join('');chart(f)}
    function chart(f){const svg=$('svg'),a=asset.history.slice(-90).map(x=>x.close),now=asset.current_price,all=[...a,now,f.low,f.target,f.high],mn=Math.min(...all)*.985,mx=Math.max(...all)*1.015,y=v=>20+(mx-v)/(mx-mn)*270,split=720,path=pts=>pts.map((p,i)=>`${i?'L':'M'}${p[0]},${p[1]}`).join(' '),ap=[...a.map((v,i)=>[20+(split-20)*i/a.length,y(v)]),[split,y(now)]],fp=[[split,y(now)],[850,y((now+f.target)/2)],[980,y(f.target)]],lo=[[split,y(now)],[850,y((now+f.low)/2)],[980,y(f.low)]],hi=[[split,y(now)],[850,y((now+f.high)/2)],[980,y(f.high)]],area=path([...hi,...lo.reverse()])+' Z';svg.innerHTML=[.2,.4,.6,.8].map(r=>`<line class="grid" x1="20" x2="980" y1="${300*r}" y2="${300*r}"/>`).join('')+`<path class="range" d="${area}"/><path class="actual" d="${path(ap)}"/><path class="prediction" d="${path(fp)}"/><line class="now" x1="${split}" x2="${split}" y1="18" y2="290"/>`}
    function openBuy(){const f=asset.forecasts.find(x=>x.key===period);$('buyInst').value=asset.inst_id;$('buyPeriod').innerHTML=asset.forecasts.map(x=>`<option value="${x.key}" ${x.key===period?'selected':''}>${x.label}</option>`).join('');$('buyPrice').value=asset.current_price;$('quantity').value='';$('notes').value='';$('buyDialog').showModal()}
    async function buy(e){e.preventDefault();const p=$('buyPeriod').value,f=asset.forecasts.find(x=>x.key===p),body={inst_id:asset.inst_id,buy_price:+$('buyPrice').value,quantity:+$('quantity').value,horizon:p,forecast_return:f.expected_return,up_probability:f.up_probability,confidence:f.confidence,target_price:f.target,notes:$('notes').value},r=await fetch('/api/spot/buy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return notify(j.error||'登记失败');$('buyDialog').close();await load();switchView('sentinel');notify('已进入持仓哨兵，开始监控卖出与止损')}
    function openSell(id,price=''){$('sellId').value=id;$('sellPrice').value=price||'';$('sellDialog').showModal()}
    async function sell(e){e.preventDefault();const r=await fetch('/api/spot/sell',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:+$('sellId').value,sell_price:+$('sellPrice').value})}),j=await r.json();if(!r.ok)return notify(j.error||'登记失败');$('sellDialog').close();notify('卖出已登记');load()}
    async function load(){try{const r=await fetch('/api/spot/positions');if(!r.ok)return;state=await r.json();records();reliability();sentinel()}catch(e){}}
    async function refreshQuotes(){try{const r=await fetch('/api/spot/quotes',{cache:'no-store'});if(!r.ok)return;const j=await r.json(),selected=asset?.inst_id;for(const fresh of j.forecasts){const existing=data.find(x=>x.inst_id===fresh.inst_id);if(existing)Object.assign(existing,fresh)}asset=data.find(x=>x.inst_id===selected)||data[0];renderRadar();render();if($('sentinelView').classList.contains('active'))load()}catch(e){}}
    function sentinel(){const open=state.positions.filter(x=>!x.sell_time),map=Object.fromEntries(state.analyses.map(x=>[x.position_id,x]));$('openCount').textContent=open.length?`· ${open.length}`:'';$('metricOpen').textContent=open.length;const pnl=state.analyses.reduce((s,x)=>s+x.unrealized_pnl,0);$('metricPnl').textContent=open.length?`${pnl>=0?'+':''}${fmt(pnl)} USDT`:'--';$('metricPnl').className=pnl>=0?'positive':'negative';$('metricRisk').textContent=state.analyses.filter(x=>x.risk_score>=60).length;$('metricExit').textContent=state.analyses.filter(x=>['reduce','exit'].includes(x.action)).length;$('positionList').innerHTML=open.length?open.map(p=>{const a=map[p.id];if(!a)return `<article class="position-card"><div class="position-name"><span>等待最新行情</span><strong>${p.inst_id}</strong></div><div class="reason position-decision">刷新行情后生成买后分析。</div></article>`;const tone=a.risk_score>=60?'high':a.risk_score>=30?'medium':'';return `<article class="position-card"><div class="position-name"><span>${labels[p.horizon]}策略 · 已持有 ${a.held_days.toFixed(1)} 天</span><strong>${p.inst_id}</strong><small>成本 ${fmt(p.buy_price)} · 数量 ${fmt(p.quantity)}</small></div><div class="position-cell"><span>当前 / 浮动收益</span><strong>${fmt(a.current_price)}</strong><small class="${a.current_return>=0?'positive':'negative'}">${pct(a.current_return)} · ${a.unrealized_pnl>=0?'+':''}${fmt(a.unrealized_pnl)} USDT</small></div><div class="position-cell"><span>动态保护位 / 目标</span><strong class="negative">${fmt(a.suggested_stop)}</strong><small>${fmt(a.target_price)}</small></div><div class="position-decision"><span class="action ${a.action}">${a.action_label} · 风险 ${a.risk_score}/100</span><div class="reason">${a.reason}</div><div class="risk-bar ${tone}"><i style="width:${a.risk_score}%"></i></div></div><button class="button" onclick="openSell(${p.id},${a.current_price})">登记卖出</button></article>`}).join(''):'<div class="empty"><strong>还没有需要监控的持仓</strong>从「机会雷达」选择股票或加密货币并手动登记买入，持仓才会进入这里。</div>'}
    function records(){$('records').innerHTML=state.positions.length?state.positions.map(x=>{const closed=!!x.sell_time,ret=closed?+x.realized_return:null;return `<tr><td><span class="tag ${closed?'closed':''}">${closed?'已完成':'持仓中'}</span></td><td><strong>${x.inst_id}</strong></td><td>${labels[x.horizon]}</td><td><strong>${fmt(x.buy_price)}</strong><br><small>${new Date(x.buy_time).toLocaleString('zh-CN')}</small></td><td>${fmt(x.quantity)}</td><td>${closed?fmt(x.sell_price):'--'}</td><td><strong class="${ret===null?'':ret>=0?'positive':'negative'}">${ret===null?'浮动中':pct(ret)}</strong></td><td>${closed?'--':`<button class="link" onclick="openSell(${x.id})">登记卖出 →</button>`}</td></tr>`}).join(''):'<tr><td colspan="8">暂无记录。点击“登记买入”开始积累真实样本。</td></tr>'}
    function reliability(){const o=state.model_evaluation.overall||{},n=o.samples||0,s=n?(o.direction_accuracy||0)*100:0,active=Object.values(state.strategy_adjustments||{}).filter(x=>x.active).length;$('ring').style.setProperty('--p',`${s}%`);$('score').textContent=n?Math.round(s):'--';$('rank').textContent=!n?'等待预测到期':active?`${active}/5 周期已自动校准`:s>=65?'方向稳定':'积累校准样本';$('reliabilityText').textContent=!n?`已有 ${o.pending||0} 个每小时预测等待到期；不依赖你的下单记录。`:`已评估 ${n} 个自身预测，方向命中率 ${s.toFixed(1)}%；每小时滚动反推，${active} 个周期已启用受限校准。`;$('periodMetrics').innerHTML=Object.entries(labels).map(([k,l])=>{const x=state.model_evaluation.by_horizon[k]||{},a=state.strategy_adjustments?.[k]||{};return `<div><span>${l}</span><strong>${x.samples?`命中 ${(x.direction_accuracy*100).toFixed(0)}%`:'等待到期'}</strong><small>${a.active?'自动校准中':`${x.samples||0} 个预测`}</small></div>`}).join('');$('adviceList').innerHTML=state.advice.map(x=>`<article class="advice-item"><span>${x.level.toUpperCase()}</span><h3>${x.title}</h3><p>${x.detail}</p></article>`).join('')}
    async function loadAssistantStatus(){try{const r=await fetch('/api/assistant/status'),j=await r.json();$('assistantModel').textContent=`${j.provider} · ${j.model}${j.configured?' · 已连接':' · 待配置 API Key'}`;$('assistantModel').classList.toggle('ready',j.configured)}catch(e){$('assistantModel').textContent='模型状态读取失败'}}
    function openAssistant(){$('assistant').classList.add('open');$('assistantQuestion').focus()}
    function addAssistantMessage(role,text,references=[]){const box=document.createElement('div');box.className=`message ${role}`;const content=document.createElement('div');content.textContent=text;box.appendChild(content);if(references.length){const refs=document.createElement('div');refs.className='assistant-evidence';references.forEach(item=>{const chip=document.createElement('span');chip.textContent=item.label;refs.appendChild(chip)});box.appendChild(refs)}$('assistantMessages').appendChild(box);$('assistantMessages').scrollTop=$('assistantMessages').scrollHeight}
    async function askAssistant(e){e.preventDefault();const question=$('assistantQuestion').value.trim();if(!question)return;addAssistantMessage('user',question);$('assistantQuestion').value='';$('assistantSend').disabled=true;$('assistantSend').textContent='关联数据中…';try{const r=await fetch('/api/assistant/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,inst_id:asset?.inst_id,horizon:period,history:assistantHistory.slice(-6)})}),j=await r.json();if(!r.ok)throw new Error(j.error||'分析失败');addAssistantMessage('assistant',j.answer,j.references||[]);assistantHistory.push({role:'user',content:question},{role:'assistant',content:j.answer})}catch(err){addAssistantMessage('system',err.message)}finally{$('assistantSend').disabled=false;$('assistantSend').textContent='分析决策'}}
    function openAdvice(){$('advice').classList.add('open')}function notify(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}init();
  </script>
</body></html>"""
